name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install dependencies
      shell: bash
      run: sudo apt install libsfml-dev cmake 

    - name: Create build dir
      run: mkdir ${{runner.workspace}}/chip8EMU/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/chip8EMU/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/chip8EMU/build
      run: cmake --build .
